In [3]:
import polars as pl

bekleyen_file = r"indirilen_raporlar\Bekleyen_Siparisler.xlsx"
hazir_file = r"indirilen_raporlar\Hazir_Siparisler.xlsx"

# 1. Read files directly into Polars as Strings
pd_bekleyen = pl.read_excel(bekleyen_file, infer_schema_length=0)
pd_hazir = pl.read_excel(hazir_file, infer_schema_length=0)

# 2. Combine them vertically
# We use how="vertical" because we forced everything to String, 
# so the schemas will match perfectly now.
sales_df = pl.concat([pd_bekleyen, pd_hazir], how="vertical")

print(sales_df.columns)

"""                pd_bekleyen = pd.read_excel(bekleyen_file)
                pd_hazir = pd.read_excel(hazir_file)
                combined_pd = pd.concat([pd_bekleyen, pd_hazir], ignore_index=True)
                self.sales_df = pl.from_pandas(combined_pd)"""

['SDM Kodu', 'SDM', 'NOKTA Kodu', 'NOKTA', 'SATIŞ TEMSİLCİSİ Kodu', 'SATIŞ TEMSİLCİSİ', 'ÜRÜN Kodu', 'ÜRÜN', 'Eski Müşteri ID', 'Erp Sevkiyat', 'Erp Fatura', 'Miktar', 'Fatura Sayısı', 'FKMS', 'Kg', 'Brüt Tutar', 'Nokta İskontosu', 'Kampanya', 'Diğer Bedelsiz', 'Toplam İndirim', 'Net Tutar', 'KDV', 'Genel Toplam', 'Kapı Sayısı']

'                pd_bekleyen = pd.read_excel(bekleyen_file)\n                pd_hazir = pd.read_excel(hazir_file)\n                combined_pd = pd.concat([pd_bekleyen, pd_hazir], ignore_index=True)\n                self.sales_df = pl.from_pandas(combined_pd)'

In [ ]:
import pandas as pd

pd_bekleyen = pd.read_excel(bekleyen_file)
pd_hazir = pd.read_excel(hazir_file)
combined_pd = pd.concat([pd_bekleyen, pd_hazir], ignore_index=True)
sales_df = pl.from_pandas(combined_pd)

NameError: name 'pd' is not defined

In [8]:
import polars as pl
bekleyen_file = r"indirilen_raporlar\Bekleyen_Siparisler.xlsx"
hazir_file = r"indirilen_raporlar\Hazir_Siparisler.xlsx"

df = pl.read_excel(bekleyen_file)
df=df.with_columns(
    pl.lit("waiting").cast(pl.Utf8).alias("status")
)
df

Could not determine dtype for column 8, falling back to string
Could not determine dtype for column 9, falling back to string
Could not determine dtype for column 10, falling back to string
Could not determine dtype for column 23, falling back to string

shape: (6, 25)
┌──────────┬─────────────┬─────────────┬─────────────┬───┬─────────┬────────────┬────────┬─────────┐
│ SDM Kodu ┆ SDM         ┆ NOKTA Kodu  ┆ NOKTA       ┆ … ┆ KDV     ┆ Genel      ┆ Kapı   ┆ status  │
│ ---      ┆ ---         ┆ ---         ┆ ---         ┆   ┆ ---     ┆ Toplam     ┆ Sayısı ┆ ---     │
│ str      ┆ str         ┆ str         ┆ str         ┆   ┆ f64     ┆ ---        ┆ ---    ┆ str     │
│          ┆             ┆             ┆             ┆   ┆         ┆ f64        ┆ str    ┆         │
╞══════════╪═════════════╪═════════════╪═════════════╪═══╪═════════╪════════════╪════════╪═════════╡
│ 1228     ┆ BEV-ANTAKYA ┆ 6137135     ┆ HATAY NURAL ┆ … ┆ 21.21   ┆ 233.27     ┆ null   ┆ waiting │
│          ┆             ┆             ┆ GIDA TARIM  ┆   ┆         ┆            ┆        ┆         │
│          ┆             ┆             ┆ SAN.VE …    ┆   ┆         ┆            ┆        ┆         │
│ 1228     ┆ BEV-ANTAKYA ┆ 6137135     ┆ HATAY NURAL ┆ … ┆ 1744.24 ┆ 19186.67   ┆ null   ┆ waiting │
│          ┆             ┆             ┆ GIDA TARIM  ┆   ┆         ┆            ┆        ┆         │
│          ┆             ┆             ┆ SAN.VE …    ┆   ┆         ┆            ┆        ┆         │
│ 1228     ┆ BEV-ANTAKYA ┆ 6137135     ┆ HATAY NURAL ┆ … ┆ 42.41   ┆ 466.55     ┆ null   ┆ waiting │
│          ┆             ┆             ┆ GIDA TARIM  ┆   ┆         ┆            ┆        ┆         │
│          ┆             ┆             ┆ SAN.VE …    ┆   ┆         ┆            ┆        ┆         │
│ 1228     ┆ BEV-ANTAKYA ┆ 6137135     ┆ HATAY NURAL ┆ … ┆ 43.61   ┆ 479.67     ┆ null   ┆ waiting │
│          ┆             ┆             ┆ GIDA TARIM  ┆   ┆         ┆            ┆        ┆         │
│          ┆             ┆             ┆ SAN.VE …    ┆   ┆         ┆            ┆        ┆         │
│ 1228     ┆ BEV-ANTAKYA ┆ 6137135     ┆ HATAY NURAL ┆ … ┆ 21.21   ┆ 233.27     ┆ null   ┆ waiting │
│          ┆             ┆             ┆ GIDA TARIM  ┆   ┆         ┆            ┆        ┆         │
│          ┆             ┆             ┆ SAN.VE …    ┆   ┆         ┆            ┆        ┆         │
│ Toplam   ┆ null        ┆ null        ┆ null        ┆ … ┆ 1872.67 ┆ 20599.42   ┆ null   ┆ waiting │
└──────────┴─────────────┴─────────────┴─────────────┴───┴─────────┴────────────┴────────┴─────────┘

In [9]:
df2 = pl.read_excel(hazir_file)
df2=df2.with_columns(
    pl.lit("ready").cast(pl.Utf8).alias("status")
)
df2

Could not determine dtype for column 9, falling back to string
Could not determine dtype for column 10, falling back to string
Could not determine dtype for column 23, falling back to string

shape: (1_013, 25)
┌──────────┬─────────────┬────────────┬─────────┬───┬───────────┬──────────┬────────┬────────┐
│ SDM Kodu ┆ SDM         ┆ NOKTA Kodu ┆ NOKTA   ┆ … ┆ KDV       ┆ Genel    ┆ Kapı   ┆ status │
│ ---      ┆ ---         ┆ ---        ┆ ---     ┆   ┆ ---       ┆ Toplam   ┆ Sayısı ┆ ---    │
│ str      ┆ str         ┆ str        ┆ str     ┆   ┆ f64       ┆ ---      ┆ ---    ┆ str    │
│          ┆             ┆            ┆         ┆   ┆           ┆ f64      ┆ str    ┆        │
╞══════════╪═════════════╪════════════╪═════════╪═══╪═══════════╪══════════╪════════╪════════╡
│ 1228     ┆ BEV-ANTAKYA ┆ 6154988    ┆ ABDO    ┆ … ┆ 37.88     ┆ 416.64   ┆ null   ┆ ready  │
│          ┆             ┆            ┆ ÖZTÜRK  ┆   ┆           ┆          ┆        ┆        │
│ 1228     ┆ BEV-ANTAKYA ┆ 6154988    ┆ ABDO    ┆ … ┆ 37.88     ┆ 416.64   ┆ null   ┆ ready  │
│          ┆             ┆            ┆ ÖZTÜRK  ┆   ┆           ┆          ┆        ┆        │
│ 1228     ┆ BEV-ANTAKYA ┆ 6154988    ┆ ABDO    ┆ … ┆ 75.75     ┆ 833.28   ┆ null   ┆ ready  │
│          ┆             ┆            ┆ ÖZTÜRK  ┆   ┆           ┆          ┆        ┆        │
│ 1228     ┆ BEV-ANTAKYA ┆ 6154988    ┆ ABDO    ┆ … ┆ 43.65     ┆ 480.2    ┆ null   ┆ ready  │
│          ┆             ┆            ┆ ÖZTÜRK  ┆   ┆           ┆          ┆        ┆        │
│ 1228     ┆ BEV-ANTAKYA ┆ 6154988    ┆ ABDO    ┆ … ┆ 43.65     ┆ 480.2    ┆ null   ┆ ready  │
│          ┆             ┆            ┆ ÖZTÜRK  ┆   ┆           ┆          ┆        ┆        │
│ …        ┆ …           ┆ …          ┆ …       ┆ … ┆ …         ┆ …        ┆ …      ┆ …      │
│ 1228     ┆ BEV-ANTAKYA ┆ 5671020    ┆ ŞEHİT   ┆ … ┆ 1.91      ┆ 193.0    ┆ null   ┆ ready  │
│          ┆             ┆            ┆ FATMA   ┆   ┆           ┆          ┆        ┆        │
│          ┆             ┆            ┆ AVLAR   ┆   ┆           ┆          ┆        ┆        │
│          ┆             ┆            ┆ BÜFESİ  ┆   ┆           ┆          ┆        ┆        │
│ 1228     ┆ BEV-ANTAKYA ┆ 5671020    ┆ ŞEHİT   ┆ … ┆ 3.82      ┆ 386.0    ┆ null   ┆ ready  │
│          ┆             ┆            ┆ FATMA   ┆   ┆           ┆          ┆        ┆        │
│          ┆             ┆            ┆ AVLAR   ┆   ┆           ┆          ┆        ┆        │
│          ┆             ┆            ┆ BÜFESİ  ┆   ┆           ┆          ┆        ┆        │
│ 1228     ┆ BEV-ANTAKYA ┆ 5671020    ┆ ŞEHİT   ┆ … ┆ 1309.05   ┆ 14399.57 ┆ null   ┆ ready  │
│          ┆             ┆            ┆ FATMA   ┆   ┆           ┆          ┆        ┆        │
│          ┆             ┆            ┆ AVLAR   ┆   ┆           ┆          ┆        ┆        │
│          ┆             ┆            ┆ BÜFESİ  ┆   ┆           ┆          ┆        ┆        │
│ 1228     ┆ BEV-ANTAKYA ┆ 5783906    ┆ ŞENOCAK ┆ … ┆ 79.59     ┆ 875.49   ┆ null   ┆ ready  │
│          ┆             ┆            ┆ MARKET  ┆   ┆           ┆          ┆        ┆        │
│          ┆             ┆            ┆ AHMET   ┆   ┆           ┆          ┆        ┆        │
│          ┆             ┆            ┆ ŞENOCAK ┆   ┆           ┆          ┆        ┆        │
│ Toplam   ┆ null        ┆ null       ┆ null    ┆ … ┆ 358770.75 ┆ 4.0899e6 ┆ null   ┆ ready  │
└──────────┴─────────────┴────────────┴─────────┴───┴───────────┴──────────┴────────┴────────┘

In [3]:
import polars as pl
bekleyen_file = r"indirilen_raporlar\Bekleyen_Siparisler.xlsx"
hazir_file = r"indirilen_raporlar\Hazir_Siparisler.xlsx"

df = pl.read_excel(bekleyen_file)
df=df.with_columns(
    pl.lit("waiting").cast(pl.Utf8).alias("status")
)
df2 = pl.read_excel(hazir_file)
df2=df2.with_columns(
    pl.lit("ready").cast(pl.Utf8).alias("status")
)
df3 = pl.concat([df, df2], how="vertical_relaxed")
df3=df3.with_columns(
    pl.col("Miktar").cast(pl.Int64),
    pl.col("Fatura Sayısı").cast(pl.Int64),
    pl.col("FKMS").cast(pl.Int64),
)
df3

Could not determine dtype for column 9, falling back to string
Could not determine dtype for column 10, falling back to string
Could not determine dtype for column 23, falling back to string
Could not determine dtype for column 9, falling back to string
Could not determine dtype for column 10, falling back to string
Could not determine dtype for column 23, falling back to string

shape: (795, 25)
┌──────────┬─────────────┬─────────────┬────────────┬───┬──────────┬────────────┬────────┬─────────┐
│ SDM Kodu ┆ SDM         ┆ NOKTA Kodu  ┆ NOKTA      ┆ … ┆ KDV      ┆ Genel      ┆ Kapı   ┆ status  │
│ ---      ┆ ---         ┆ ---         ┆ ---        ┆   ┆ ---      ┆ Toplam     ┆ Sayısı ┆ ---     │
│ str      ┆ str         ┆ str         ┆ str        ┆   ┆ f64      ┆ ---        ┆ ---    ┆ str     │
│          ┆             ┆             ┆            ┆   ┆          ┆ f64        ┆ str    ┆         │
╞══════════╪═════════════╪═════════════╪════════════╪═══╪══════════╪════════════╪════════╪═════════╡
│ 1228     ┆ BEV-ANTAKYA ┆ 6045512     ┆ ABDULKADİR ┆ … ┆ 136.37   ┆ 1500.1     ┆ null   ┆ waiting │
│          ┆             ┆             ┆ KORKUT     ┆   ┆          ┆            ┆        ┆         │
│ 1228     ┆ BEV-ANTAKYA ┆ 6045512     ┆ ABDULKADİR ┆ … ┆ 377.25   ┆ 4149.8     ┆ null   ┆ waiting │
│          ┆             ┆             ┆ KORKUT     ┆   ┆          ┆            ┆        ┆         │
│ 1228     ┆ BEV-ANTAKYA ┆ 6045512     ┆ ABDULKADİR ┆ … ┆ 65.57    ┆ 721.31     ┆ null   ┆ waiting │
│          ┆             ┆             ┆ KORKUT     ┆   ┆          ┆            ┆        ┆         │
│ 1228     ┆ BEV-ANTAKYA ┆ 5890412     ┆ ABDULLAH   ┆ … ┆ 188.63   ┆ 2074.9     ┆ null   ┆ waiting │
│          ┆             ┆             ┆ UÇAR       ┆   ┆          ┆            ┆        ┆         │
│ 1228     ┆ BEV-ANTAKYA ┆ 5890412     ┆ ABDULLAH   ┆ … ┆ 32.79    ┆ 360.66     ┆ null   ┆ waiting │
│          ┆             ┆             ┆ UÇAR       ┆   ┆          ┆            ┆        ┆         │
│ …        ┆ …           ┆ …           ┆ …          ┆ … ┆ …        ┆ …          ┆ …      ┆ …       │
│ 1228     ┆ BEV-ANTAKYA ┆ 5724044     ┆ ŞAH İTH    ┆ … ┆ 87.31    ┆ 960.4      ┆ null   ┆ ready   │
│          ┆             ┆             ┆ İHR        ┆   ┆          ┆            ┆        ┆         │
│          ┆             ┆             ┆ BAKLİYAT   ┆   ┆          ┆            ┆        ┆         │
│          ┆             ┆             ┆ AKARYAKIT… ┆   ┆          ┆            ┆        ┆         │
│ 1228     ┆ BEV-ANTAKYA ┆ 5724044     ┆ ŞAH İTH    ┆ … ┆ 179.5    ┆ 1974.52    ┆ null   ┆ ready   │
│          ┆             ┆             ┆ İHR        ┆   ┆          ┆            ┆        ┆         │
│          ┆             ┆             ┆ BAKLİYAT   ┆   ┆          ┆            ┆        ┆         │
│          ┆             ┆             ┆ AKARYAKIT… ┆   ┆          ┆            ┆        ┆         │
│ 1228     ┆ BEV-ANTAKYA ┆ 5724044     ┆ ŞAH İTH    ┆ … ┆ 136.37   ┆ 1500.1     ┆ null   ┆ ready   │
│          ┆             ┆             ┆ İHR        ┆   ┆          ┆            ┆        ┆         │
│          ┆             ┆             ┆ BAKLİYAT   ┆   ┆          ┆            ┆        ┆         │
│          ┆             ┆             ┆ AKARYAKIT… ┆   ┆          ┆            ┆        ┆         │
│ 1228     ┆ BEV-ANTAKYA ┆ 5724044     ┆ ŞAH İTH    ┆ … ┆ 188.63   ┆ 2074.9     ┆ null   ┆ ready   │
│          ┆             ┆             ┆ İHR        ┆   ┆          ┆            ┆        ┆         │
│          ┆             ┆             ┆ BAKLİYAT   ┆   ┆          ┆            ┆        ┆         │
│          ┆             ┆             ┆ AKARYAKIT… ┆   ┆          ┆            ┆        ┆         │
│ Toplam   ┆ null        ┆ null        ┆ null       ┆ … ┆ 26811.65 ┆ 309804.34  ┆ null   ┆ ready   │
└──────────┴─────────────┴─────────────┴────────────┴───┴──────────┴────────────┴────────┴─────────┘

In [4]:
df3 = pl.concat([df, df2], how="vertical_relaxed")
df3

shape: (795, 25)
┌──────────┬─────────────┬─────────────┬────────────┬───┬──────────┬────────────┬────────┬─────────┐
│ SDM Kodu ┆ SDM         ┆ NOKTA Kodu  ┆ NOKTA      ┆ … ┆ KDV      ┆ Genel      ┆ Kapı   ┆ status  │
│ ---      ┆ ---         ┆ ---         ┆ ---        ┆   ┆ ---      ┆ Toplam     ┆ Sayısı ┆ ---     │
│ str      ┆ str         ┆ str         ┆ str        ┆   ┆ f64      ┆ ---        ┆ ---    ┆ str     │
│          ┆             ┆             ┆            ┆   ┆          ┆ f64        ┆ str    ┆         │
╞══════════╪═════════════╪═════════════╪════════════╪═══╪══════════╪════════════╪════════╪═════════╡
│ 1228     ┆ BEV-ANTAKYA ┆ 6045512     ┆ ABDULKADİR ┆ … ┆ 136.37   ┆ 1500.1     ┆ null   ┆ waiting │
│          ┆             ┆             ┆ KORKUT     ┆   ┆          ┆            ┆        ┆         │
│ 1228     ┆ BEV-ANTAKYA ┆ 6045512     ┆ ABDULKADİR ┆ … ┆ 377.25   ┆ 4149.8     ┆ null   ┆ waiting │
│          ┆             ┆             ┆ KORKUT     ┆   ┆          ┆            ┆        ┆         │
│ 1228     ┆ BEV-ANTAKYA ┆ 6045512     ┆ ABDULKADİR ┆ … ┆ 65.57    ┆ 721.31     ┆ null   ┆ waiting │
│          ┆             ┆             ┆ KORKUT     ┆   ┆          ┆            ┆        ┆         │
│ 1228     ┆ BEV-ANTAKYA ┆ 5890412     ┆ ABDULLAH   ┆ … ┆ 188.63   ┆ 2074.9     ┆ null   ┆ waiting │
│          ┆             ┆             ┆ UÇAR       ┆   ┆          ┆            ┆        ┆         │
│ 1228     ┆ BEV-ANTAKYA ┆ 5890412     ┆ ABDULLAH   ┆ … ┆ 32.79    ┆ 360.66     ┆ null   ┆ waiting │
│          ┆             ┆             ┆ UÇAR       ┆   ┆          ┆            ┆        ┆         │
│ …        ┆ …           ┆ …           ┆ …          ┆ … ┆ …        ┆ …          ┆ …      ┆ …       │
│ 1228     ┆ BEV-ANTAKYA ┆ 5724044     ┆ ŞAH İTH    ┆ … ┆ 87.31    ┆ 960.4      ┆ null   ┆ ready   │
│          ┆             ┆             ┆ İHR        ┆   ┆          ┆            ┆        ┆         │
│          ┆             ┆             ┆ BAKLİYAT   ┆   ┆          ┆            ┆        ┆         │
│          ┆             ┆             ┆ AKARYAKIT… ┆   ┆          ┆            ┆        ┆         │
│ 1228     ┆ BEV-ANTAKYA ┆ 5724044     ┆ ŞAH İTH    ┆ … ┆ 179.5    ┆ 1974.52    ┆ null   ┆ ready   │
│          ┆             ┆             ┆ İHR        ┆   ┆          ┆            ┆        ┆         │
│          ┆             ┆             ┆ BAKLİYAT   ┆   ┆          ┆            ┆        ┆         │
│          ┆             ┆             ┆ AKARYAKIT… ┆   ┆          ┆            ┆        ┆         │
│ 1228     ┆ BEV-ANTAKYA ┆ 5724044     ┆ ŞAH İTH    ┆ … ┆ 136.37   ┆ 1500.1     ┆ null   ┆ ready   │
│          ┆             ┆             ┆ İHR        ┆   ┆          ┆            ┆        ┆         │
│          ┆             ┆             ┆ BAKLİYAT   ┆   ┆          ┆            ┆        ┆         │
│          ┆             ┆             ┆ AKARYAKIT… ┆   ┆          ┆            ┆        ┆         │
│ 1228     ┆ BEV-ANTAKYA ┆ 5724044     ┆ ŞAH İTH    ┆ … ┆ 188.63   ┆ 2074.9     ┆ null   ┆ ready   │
│          ┆             ┆             ┆ İHR        ┆   ┆          ┆            ┆        ┆         │
│          ┆             ┆             ┆ BAKLİYAT   ┆   ┆          ┆            ┆        ┆         │
│          ┆             ┆             ┆ AKARYAKIT… ┆   ┆          ┆            ┆        ┆         │
│ Toplam   ┆ null        ┆ null        ┆ null       ┆ … ┆ 26811.65 ┆ 309804.34  ┆ null   ┆ ready   │
└──────────┴─────────────┴─────────────┴────────────┴───┴──────────┴────────────┴────────┴─────────┘

In [5]:
df.group_by("SATIŞ TEMSİLCİSİ").agg(pl.col("Miktar").sum())

shape: (8, 2)
┌───────────────────┬────────┐
│ SATIŞ TEMSİLCİSİ  ┆ Miktar │
│ ---               ┆ ---    │
│ str               ┆ i64    │
╞═══════════════════╪════════╡
│ METİN ANASIZ      ┆ 256    │
│ null              ┆ 2610   │
│ OĞUZHAN DURMAZ    ┆ 240    │
│ SELİMCAN TUNER    ┆ 637    │
│ SERAY AKSOY       ┆ 304    │
│ GÖRKEM DOKSÖZ     ┆ 428    │
│ AVNİ DOĞRU        ┆ 460    │
│ MUSTAFA DELİLOĞLU ┆ 285    │
└───────────────────┴────────┘

In [6]:
from palet_sayisi import Palet_Hesaplama
sales_df =df
customer_df = pl.read_excel(r"data\Müşteri Listesi.xlsx")
pallet_df = pl.read_excel(r"data\Palet Koli Raporu.xlsx")
palet_hesaplama = Palet_Hesaplama(sales_df, customer_df, pallet_df)
palet_hesaplama=pl.from_pandas(palet_hesaplama)
palet_hesaplama.group_by("SATIŞ_TEMSİLCİSİ").agg(pl.col("Miktar").sum() ,pl.col("Palet_Sayısı").sum()  ).sort("Miktar", descending=True)

Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 5, falling back to string
Could not determine dtype for column 7, falling back to string
Could not determine dtype for column 27, falling back to string
Could not determine dtype for column 50, falling back to string
Could not determine dtype for column 51, falling back to string
Could not determine dtype for column 52, falling back to string
Could not determine dtype for column 53, falling back to string
Could not determine dtype for column 54, falling back to string
Could not determine dtype for column 55, falling back to string
Could not determine dtype for column 57, falling back to string
Could not determine dtype for column 74, falling back to string
Could not determine dtype for column 75, falling back to string
Could not determine dtype for column 77, falling back to string
Could not determine dtype for column 96, falling back to string
Could not determine dtype for column 97, falling back to string
Could not determine dtype for column 7, falling back to string
Could not determine dtype for column 8, falling back to string
Could not determine dtype for column 9, falling back to string

shape: (7, 3)
┌───────────────────┬────────┬──────────────┐
│ SATIŞ_TEMSİLCİSİ  ┆ Miktar ┆ Palet_Sayısı │
│ ---               ┆ ---    ┆ ---          │
│ str               ┆ i64    ┆ f64          │
╞═══════════════════╪════════╪══════════════╡
│ SELİMCAN TUNER    ┆ 637    ┆ 8.851947     │
│ AVNİ DOĞRU        ┆ 460    ┆ 6.085818     │
│ GÖRKEM DOKSÖZ     ┆ 428    ┆ 5.31327      │
│ SERAY AKSOY       ┆ 304    ┆ 4.126892     │
│ MUSTAFA DELİLOĞLU ┆ 285    ┆ 3.344848     │
│ METİN ANASIZ      ┆ 275    ┆ 3.706101     │
│ OĞUZHAN DURMAZ    ┆ 240    ┆ 3.353707     │
└───────────────────┴────────┴──────────────┘

In [7]:
from palet_sayisi import Palet_Hesaplama
sales_df =df2
customer_df = pl.read_excel(r"data\Müşteri Listesi.xlsx")
pallet_df = pl.read_excel(r"data\Palet Koli Raporu.xlsx")
palet_hesaplama = Palet_Hesaplama(sales_df, customer_df, pallet_df)
palet_hesaplama=pl.from_pandas(palet_hesaplama)
palet_hesaplama.group_by("SATIŞ_TEMSİLCİSİ").agg(pl.col("Miktar").sum() ,pl.col("Palet_Sayısı").sum()  ).sort("Miktar", descending=True)

Could not determine dtype for column 4, falling back to string
Could not determine dtype for column 5, falling back to string
Could not determine dtype for column 7, falling back to string
Could not determine dtype for column 27, falling back to string
Could not determine dtype for column 50, falling back to string
Could not determine dtype for column 51, falling back to string
Could not determine dtype for column 52, falling back to string
Could not determine dtype for column 53, falling back to string
Could not determine dtype for column 54, falling back to string
Could not determine dtype for column 55, falling back to string
Could not determine dtype for column 57, falling back to string
Could not determine dtype for column 74, falling back to string
Could not determine dtype for column 75, falling back to string
Could not determine dtype for column 77, falling back to string
Could not determine dtype for column 96, falling back to string
Could not determine dtype for column 97, falling back to string
Could not determine dtype for column 7, falling back to string
Could not determine dtype for column 8, falling back to string
Could not determine dtype for column 9, falling back to string

shape: (5, 3)
┌──────────────────┬────────┬──────────────┐
│ SATIŞ_TEMSİLCİSİ ┆ Miktar ┆ Palet_Sayısı │
│ ---              ┆ ---    ┆ ---          │
│ str              ┆ i64    ┆ f64          │
╞══════════════════╪════════╪══════════════╡
│ ASLI OFLAZ       ┆ 254    ┆ 3.463689     │
│ AVNİ DOĞRU       ┆ 178    ┆ 2.529919     │
│ ABDULGANİ GÜLER  ┆ 178    ┆ 2.391819     │
│ ONUR CAN DİKBAŞ  ┆ 139    ┆ 1.725625     │
│ SERKAN BOYAR     ┆ 97     ┆ 1.39646      │
└──────────────────┴────────┴──────────────┘